### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by gacphillips** [dehorsley/colette#4]
Lines 47-52 (copy/pasted below) the 'list' is trying to do something it can't (from what I can figure out from the error message).

Round = list[Person]
Pairing = dict[Person, Pair]
Cost = float

def find_optimal_pairs(N, weights) -> list[tuple[int, int]]:

**Comment by dehorsley** [comment]
Ah yes this is a Python 3.9 feature. It doesn't actually affect behaviour at runtime, just a type checking, so can perhaps be safely removed if we want to support Python version < 3.9.

Closed for now.
