### ISSUE TITLE
can i get some push access pls?

### ISSUE THREAD

**Issue by gacphillips** [dehorsley/colette#7]
I have the paper outline but can't push it to the repository.  Or we use the one I made?

**Comment by dehorsley** [comment]
I think it'd be better to have the paper source a different repo. I think having them together is going to create more of a hassle than a benefit as they're going to be managed pretty much independently. That is, you'll have to worry about merging in changes that aren't relevant to the project you're working on. 

Perhaps you have a good argument to put them in the same repo though?
